import { WebhookClient } from 'discord.js';
import {
  DISCORD_MINTING_ACTIVITY_WEBHOOK_ID,
  DISCORD_MINTING_ACTIVITY_WEBHOOK_TOKEN,
  DISCORD_VERDICT_ACTIVITY_WEBHOOK_ID,
  DISCORD_VERDICT_ACTIVITY_WEBHOOK_TOKEN,
} from '../constants';

export const client = new WebhookClient(
  DISCORD_VERDICT_ACTIVITY_WEBHOOK_ID,
  DISCORD_VERDICT_ACTIVITY_WEBHOOK_TOKEN,
);

export const mintingClient = new WebhookClient(
  DISCORD_MINTING_ACTIVITY_WEBHOOK_ID,
  DISCORD_MINTING_ACTIVITY_WEBHOOK_TOKEN,
);
